COM-18-Implement-Global-Error-Handling
valentyna-koshelnyk/ecommerce-spring-api-prototype pull request #18
Opened 2024-01-19 08:01 UTC by valentyna-koshelnyk

2024-01-19 16:10 UTC, MenilV commented
This PR now has confilicts, let's resolve them first before reviewing.

2024-01-19 16:23 UTC, valentyna-koshelnyk commented
> This PR now has confilicts, let's resolve them first before reviewing.

@MenilV resolved :)

2024-01-22 18:34 UTC, MenilV requested changes
A few things to check but good overall.

2024-01-22 18:34 UTC, MenilV commented on src/main/java/com/startsteps/ecommerceapi/user/config/Swagger2Configuration.java
do we need this file now?

2024-01-22 18:34 UTC, MenilV commented on src/main/java/com/startsteps/ecommerceapi/user/security/jwt/JwtUtil.java
> +
do we need this?

2024-01-23 14:06 UTC, MenilV approved these changes
nice!

2024-01-23 14:06 UTC, MenilV commented on src/main/resources/application-dev.yml
> +    expiresIn: 300000000
this seems like a lot (3.5 days)

2024-01-23 14:09 UTC, merged